apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
type: Opaque
data:
  ENV_VAR1: {{ .Values.environment.ENV_VAR1 | b64enc | quote }}
  ENV_VAR2: {{ .Values.environment.ENV_VAR2 | b64enc | quote }}
  ENV_VAR3: {{ .Values.environment.ENV_VAR3 | b64enc | quote }}
  SECRET_ENV_VAR1: {{ .Values.environment_secrets.SECRET_ENV_VAR1 | b64enc | quote }}