apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    service: {{.Values.service.name}}
spec:
  selector:
    app: <pod-name>
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000