creation_rules:
#  https://github.com/mozilla/sops#encrypting-using-gcp-kms
#  gcloud kms keyrings create sops --location global
#  gcloud kms keys create sops-key --location global --keyring sops --purpose encryption
#  gcloud kms keys list --location global --keyring sops
  - gcp_kms: <gcp-kms-key> # it would be something like this -> projects/my-project/locations/global/keyRings/sops/cryptoKeys/sops-key