# to obtain a file like this one
# create secrets.yaml file with this content:
# environment_secrets:
#   SECRET_ENV_VAR1: secret-env-var
# Then to encrypt the file execute the next command -> sops --encrypt --gcp-kms projects/my-project/locations/global/keyRings/sops/cryptoKeys/sops-key secrets.yaml

environment_secrets:
    SECRET_ENV_VAR1: ENC[AES256_GCM,data:CwE4O1s=,iv:2k=,aad:o=,tag:w==]
sops:
    kms: []
    gcp_kms:
        - resource_id: "here will be automatically created what you used as argument of --gcp-kms in your command"
          created_at: "2022-07-09T11:07:40Z"
          enc: CiQAm3ShjLMz/3HjonxQfdfafwdxeMD4fYcggUigyCLXnpNcSSQD//ssHivdDTCy1n5zSibmSVzabt/V+xqOFoger
    hc_vault: []
    age: []
    lastmodified: "2022-07-09T11:07:40Z"
    mac: ENC[AES256_GCM,data:CwE4O1s=,iv:2k=,aad:o=,tag:w==]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
